#pragma once
#include QMK_KEYBOARD_H

enum unicode_names {
        ALPHA,
        ALEPH,
        BETA,
        GAMMA,
        C_GAMMA,
        DELTA,
        C_DELTA,
        EPSILON,
        ZETA,
        ETA,
        THETA,
        C_THETA,
        IOTA,
        KAPPA,
        LAMBDA,
        C_LAMBDA,
        MU,
        NU,
        XI,
        C_XI,
        PI,
        C_PI,
        RHO,
        SIGMA,
        C_SIGMA,
        TAU,
        PHI,
        C_PHI,
        CHI,
        PSI,
        C_PSI,
        OMEGA,
        C_OMEGA,
        PARTIAL,
        INTEGRAL,
        ALMST_EQL
};

// Where possible, unicode values for the math symbols
// are preferred over actual Greek letters.
const uint32_t PROGMEM unicode_map[] = {
    [ALPHA]  = 0x03B1,
    [ALEPH]  = 0x2135,
    [BETA]  = 0x03B2,
    [GAMMA]  = 0x03B3,
    [C_GAMMA]  = 0x0393,
    [DELTA]  = 0x03B4,
    [C_DELTA]  = 0x2206,
    [EPSILON]  = 0x2107,
    [ZETA]  = 0x03B6,
    [ETA]  = 0x03B7,
    [THETA]  = 0x03B8,
    [C_THETA]  = 0x0398,
    [IOTA]  = 0x03B9,
    [KAPPA]  = 0x03BA,
    [LAMBDA]  = 0x03BB,
    [C_LAMBDA]  = 0x039B,
    [MU]  = 0x00B5,
    [NU]  = 0x03BD,
    [XI]  = 0x03BE,
    [C_XI]  = 0x039E,
    [PI]  = 0x03C0,
    [C_PI]  = 0x03A0,
    [RHO]  = 0x03C1,
    [SIGMA]  = 0x03C3,
    [C_SIGMA]  = 0x2211,
    [TAU]  = 0x03C4,
    [PHI]  = 0x03C6,
    [C_PHI]  = 0x03A6,
    [CHI]  = 0x03C7,
    [PSI]  = 0x03C8,
    [C_PSI]  = 0x03A8,
    [OMEGA]  = 0x03C9,
    [C_OMEGA]  = 0x03A9,
    [PARTIAL]  = 0x2202,
    [INTEGRAL]  = 0x222B,
    [ALMST_EQL]  = 0x2248,
};
